# Generated by Django 6.0.3 on 2026-03-12 22:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school_id", models.UUIDField()),
                ("academic_year", models.CharField(max_length=9)),
                ("term", models.CharField(max_length=8)),
                ("form_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_by", models.UUIDField()),
                ("status", models.CharField(default="draft", max_length=24)),
                ("code", models.CharField(max_length=9, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school_id", models.UUIDField()),
                ("academic_year", models.CharField(max_length=9)),
                ("term", models.CharField(max_length=8)),
                ("form_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_by", models.UUIDField()),
                ("status", models.CharField(default="draft", max_length=24)),
                ("full_name_ar", models.CharField(max_length=128)),
                ("phone", models.CharField(max_length=32)),
                ("relation", models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school_id", models.UUIDField()),
                ("academic_year", models.CharField(max_length=9)),
                ("term", models.CharField(max_length=8)),
                ("form_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_by", models.UUIDField()),
                ("status", models.CharField(default="draft", max_length=24)),
                ("name_ar", models.CharField(max_length=256)),
                (
                    "moe_code",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("level", models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school_id", models.UUIDField()),
                ("academic_year", models.CharField(max_length=9)),
                ("term", models.CharField(max_length=8)),
                ("form_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_by", models.UUIDField()),
                ("status", models.CharField(default="draft", max_length=24)),
                ("national_id", models.CharField(max_length=32, unique=True)),
                ("first_name_ar", models.CharField(max_length=64)),
                ("last_name_ar", models.CharField(max_length=64)),
                ("dob", models.DateField()),
                ("nationality", models.CharField(blank=True, max_length=64, null=True)),
                ("pdppl_guardian_consent", models.BooleanField(default=False)),
                ("consent_ts", models.DateTimeField(blank=True, null=True)),
                (
                    "guardian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.guardian",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academic_year", models.CharField(max_length=9)),
                ("term", models.CharField(max_length=8)),
                ("form_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_by", models.UUIDField()),
                ("status", models.CharField(default="draft", max_length=24)),
                ("grade", models.CharField(max_length=16)),
                ("section", models.CharField(blank=True, max_length=8, null=True)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "school", "year", "grade", "section")},
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school_id", models.UUIDField()),
                ("academic_year", models.CharField(max_length=9)),
                ("term", models.CharField(max_length=8)),
                ("form_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_by", models.UUIDField()),
                ("status", models.CharField(default="draft", max_length=24)),
                ("code", models.CharField(max_length=8)),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="students.academicyear",
                    ),
                ),
            ],
            options={
                "unique_together": {("year", "code")},
            },
        ),
    ]
