# Generated by Django 6.0.3 on 2026-03-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "students",
            "0002_alter_enrollment_form_uuid_alter_guardian_form_uuid_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="guardian",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="student",
            name="created_by",
        ),
    ]
