# Generated by Django 5.1 on 2026-03-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("status", models.CharField(max_length=10)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="people.staff"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("period", models.SmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "حاضر"),
                            ("absent", "غائب"),
                            ("late", "متأخر"),
                            ("excused", "معذور"),
                        ],
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.enrollment",
                    ),
                ),
            ],
            options={
                "unique_together": {("enrollment", "date", "period")},
            },
        ),
    ]
