# Generated by Django 5.0.3 on 2026-03-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_attendancerecord_id_delete_staffattendance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendancerecord",
            options={
                "verbose_name": "سجل حضور طالب",
                "verbose_name_plural": "سجلات حضور الطلبة",
            },
        ),
    ]
