# Generated by Django 6.0.3 on 2026-03-13 03:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NoticeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="معرّف السجل",
                    ),
                ),
                (
                    "school_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="معرّف المدرسة"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="السنة الأكاديمية",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="الفصل الدراسي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("final", "نهائي"),
                            ("archived", "مؤرشف"),
                        ],
                        default="draft",
                        max_length=24,
                        verbose_name="حالة السجل",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="رمز القالب"
                    ),
                ),
                ("channel", models.CharField(max_length=16, verbose_name="القناة")),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="الموضوع"
                    ),
                ),
                ("body", models.TextField(verbose_name="نص الرسالة")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منشئ السجل",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="معرّف السجل",
                    ),
                ),
                (
                    "school_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="معرّف المدرسة"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="السنة الأكاديمية",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="الفصل الدراسي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("final", "نهائي"),
                            ("archived", "مؤرشف"),
                        ],
                        default="draft",
                        max_length=24,
                        verbose_name="حالة السجل",
                    ),
                ),
                (
                    "notice_type",
                    models.CharField(max_length=32, verbose_name="نوع الإشعار"),
                ),
                ("channel", models.CharField(max_length=32, verbose_name="القناة")),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإرسال"
                    ),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, null=True, verbose_name="البيانات"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منشئ السجل",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.noticetemplate",
                        verbose_name="القالب",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
