# Generated by Django 6.0.3 on 2026-03-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notice_form_uuid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notice",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="noticetemplate",
            name="created_by",
        ),
    ]
