
version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: shahania_db
      POSTGRES_USER: sh_user
      POSTGRES_PASSWORD: StrongPass!
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  web:
    build: .
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.prod
      PG_NAME: shahania_db
      PG_USER: sh_user
      PG_PASSWORD: StrongPass!
      PG_HOST: db
      PG_PORT: 5432
      REDIS_URL: redis://redis:6379/0
    depends_on: [db, redis]
    ports: ["8000:8000"]
  worker:
    build: .
    command: celery -A core worker -l info
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.prod
      PG_NAME: shahania_db
      PG_USER: sh_user
      PG_PASSWORD: StrongPass!
      PG_HOST: db
      PG_PORT: 5432
      REDIS_URL: redis://redis:6379/0
    depends_on: [db, redis]
volumes:
  dbdata:
