# Generated by Django 6.0.3 on 2026-03-13 03:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationalplanitem",
            name="form_uuid",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                null=True,
                unique=True,
                verbose_name="معرّف السجل",
            ),
        ),
        migrations.AlterField(
            model_name="qualitycommittee",
            name="form_uuid",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                null=True,
                unique=True,
                verbose_name="معرّف السجل",
            ),
        ),
        migrations.AlterField(
            model_name="qualitydomain",
            name="form_uuid",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                null=True,
                unique=True,
                verbose_name="معرّف السجل",
            ),
        ),
        migrations.AlterField(
            model_name="qualityindicator",
            name="form_uuid",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                null=True,
                unique=True,
                verbose_name="معرّف السجل",
            ),
        ),
        migrations.AlterField(
            model_name="qualitytarget",
            name="form_uuid",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                null=True,
                unique=True,
                verbose_name="معرّف السجل",
            ),
        ),
    ]
