# Generated by Django 6.0.3 on 2026-03-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0002_alter_operationalplanitem_form_uuid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationalplanitem",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="qualitycommittee",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="qualitydomain",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="qualityindicator",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="qualitytarget",
            name="created_by",
        ),
    ]
