# Generated by Django 5.0.3 on 2026-03-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0002_alter_clinicvisit_id_delete_medicationlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clinicvisit",
            options={
                "verbose_name": "زيارة عيادة",
                "verbose_name_plural": "زيارات العيادة",
            },
        ),
    ]
