# Generated by Django 5.0.3 on 2026-03-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_school_created_at_remove_school_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classroom",
            options={"verbose_name": "شعبة صف", "verbose_name_plural": "شُعب الصفوف"},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "verbose_name": "قاعة/غرفة",
                "verbose_name_plural": "القاعات/الغرف",
            },
        ),
        migrations.AlterModelOptions(
            name="school",
            options={"verbose_name": "مدرسة", "verbose_name_plural": "المدارس"},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"verbose_name": "مادة", "verbose_name_plural": "المواد"},
        ),
        migrations.AlterModelOptions(
            name="term",
            options={
                "verbose_name": "فصل دراسي",
                "verbose_name_plural": "الفصول الدراسية",
            },
        ),
        migrations.AlterModelOptions(
            name="year",
            options={
                "verbose_name": "عام دراسي",
                "verbose_name_plural": "الأعوام الدراسية",
            },
        ),
    ]
