# Generated by Django 6.0.3 on 2026-03-12 22:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school_id", models.UUIDField()),
                ("academic_year", models.CharField(max_length=9)),
                ("form_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_by", models.UUIDField()),
                ("status", models.CharField(default="draft", max_length=24)),
                ("exam_type", models.CharField(max_length=32)),
                ("date", models.DateField()),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.subject",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="students.term"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExamResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school_id", models.UUIDField()),
                ("academic_year", models.CharField(max_length=9)),
                ("term", models.CharField(max_length=8)),
                ("form_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_by", models.UUIDField()),
                ("status", models.CharField(default="draft", max_length=24)),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade", models.CharField(max_length=16)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.enrollment",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.exam",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExamSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school_id", models.UUIDField()),
                ("academic_year", models.CharField(max_length=9)),
                ("term", models.CharField(max_length=8)),
                ("form_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_by", models.UUIDField()),
                ("status", models.CharField(default="draft", max_length=24)),
                ("scheduled_at", models.DateTimeField()),
                ("room", models.CharField(max_length=64)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.exam",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
