# Generated by Django 6.0.3 on 2026-03-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0002_alter_exam_form_uuid_alter_examresult_form_uuid_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="examresult",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="examsession",
            name="created_by",
        ),
    ]
