# Generated by Django 6.0.3 on 2026-03-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_alter_leaverequest_form_uuid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaverequest",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="performancereview",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="staffattendance",
            name="created_by",
        ),
    ]
