# Generated by Django 6.0.3 on 2026-03-12 22:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school_id", models.UUIDField()),
                ("academic_year", models.CharField(max_length=9)),
                ("term", models.CharField(max_length=8)),
                ("form_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_by", models.UUIDField()),
                ("status", models.CharField(default="draft", max_length=24)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name_ar", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClassRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academic_year", models.CharField(max_length=9)),
                ("term", models.CharField(max_length=8)),
                ("form_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_by", models.UUIDField()),
                ("status", models.CharField(default="draft", max_length=24)),
                ("grade", models.CharField(max_length=16)),
                ("section", models.CharField(max_length=8)),
                ("capacity", models.SmallIntegerField(blank=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.school",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
            ],
            options={
                "unique_together": {("school", "year", "grade", "section")},
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school_id", models.UUIDField()),
                ("academic_year", models.CharField(max_length=9)),
                ("term", models.CharField(max_length=8)),
                ("form_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_by", models.UUIDField()),
                ("status", models.CharField(default="draft", max_length=24)),
                ("full_name_ar", models.CharField(max_length=128)),
                ("phone", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TeachingAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school_id", models.UUIDField()),
                ("academic_year", models.CharField(max_length=9)),
                ("term", models.CharField(max_length=8)),
                ("form_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_by", models.UUIDField()),
                ("status", models.CharField(default="draft", max_length=24)),
                (
                    "class_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.classroom",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.teacher",
                    ),
                ),
            ],
            options={
                "unique_together": {("teacher", "subject", "class_room")},
            },
        ),
    ]
