# Generated by Django 6.0.3 on 2026-03-13 03:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicyear",
            name="form_uuid",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                null=True,
                unique=True,
                verbose_name="معرّف السجل",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="form_uuid",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                null=True,
                unique=True,
                verbose_name="معرّف السجل",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="form_uuid",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                null=True,
                unique=True,
                verbose_name="معرّف السجل",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="form_uuid",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                null=True,
                unique=True,
                verbose_name="معرّف السجل",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="form_uuid",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                null=True,
                unique=True,
                verbose_name="معرّف السجل",
            ),
        ),
        migrations.AlterField(
            model_name="teachingassignment",
            name="form_uuid",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                null=True,
                unique=True,
                verbose_name="معرّف السجل",
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="form_uuid",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                null=True,
                unique=True,
                verbose_name="معرّف السجل",
            ),
        ),
    ]
