# Generated by Django 6.0.3 on 2026-03-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_alter_academicyear_form_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="level",
            field=models.CharField(
                choices=[
                    ("preparatory", "إعدادي"),
                    ("secondary", "ثانوي"),
                    ("grouped", "مدرسة مجموعة مع إعدادي ثانوي"),
                ],
                max_length=32,
                verbose_name="المرحلة",
            ),
        ),
    ]
