# Generated by Django 6.0.3 on 2026-03-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_alter_school_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="level",
            field=models.CharField(
                choices=[
                    ("primary", "ابتدائي"),
                    ("preparatory", "إعدادي"),
                    ("secondary", "ثانوي"),
                    ("grouped", "مجمعة"),
                ],
                max_length=32,
                verbose_name="المرحلة",
            ),
        ),
    ]
