# Generated by Django 6.0.3 on 2026-03-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_alter_school_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academicyear",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="classroom",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="school",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="teachingassignment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="term",
            name="created_by",
        ),
    ]
