# Generated by Django 6.0.3 on 2026-03-13 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_remove_academicyear_created_by_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="classroom",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to="academics.term",
                verbose_name="الفصل الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to="academics.academicyear",
                verbose_name="السنة الأكاديمية",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classroom",
            unique_together={("school", "year", "term", "grade", "section")},
        ),
    ]
