# Generated by Django 6.0.3 on 2026-03-13 03:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="معرّف السجل",
                    ),
                ),
                (
                    "school_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="معرّف المدرسة"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="السنة الأكاديمية",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="الفصل الدراسي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("final", "نهائي"),
                            ("archived", "مؤرشف"),
                        ],
                        default="draft",
                        max_length=24,
                        verbose_name="حالة السجل",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="اسم الغرفة")),
                (
                    "capacity",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="السعة"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="النوع"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منشئ السجل",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TimetableRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="معرّف السجل",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="السنة الأكاديمية",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="الفصل الدراسي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("final", "نهائي"),
                            ("archived", "مؤرشف"),
                        ],
                        default="draft",
                        max_length=24,
                        verbose_name="حالة السجل",
                    ),
                ),
                ("json_rule", models.JSONField(verbose_name="القاعدة")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منشئ السجل",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.academicyear",
                        verbose_name="السنة",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TimetableSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="معرّف السجل",
                    ),
                ),
                (
                    "school_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="معرّف المدرسة"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="السنة الأكاديمية",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="الفصل الدراسي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("final", "نهائي"),
                            ("archived", "مؤرشف"),
                        ],
                        default="draft",
                        max_length=24,
                        verbose_name="حالة السجل",
                    ),
                ),
                ("day_of_week", models.SmallIntegerField(verbose_name="اليوم")),
                ("period", models.SmallIntegerField(verbose_name="الحصة")),
                ("is_fixed", models.BooleanField(default=False, verbose_name="ثابت")),
                (
                    "class_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.classroom",
                        verbose_name="الفصل",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منشئ السجل",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="timetable.room",
                        verbose_name="الغرفة",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.subject",
                        verbose_name="المادة",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.teacher",
                        verbose_name="المعلم",
                    ),
                ),
            ],
            options={
                "unique_together": {("class_room", "day_of_week", "period")},
            },
        ),
    ]
