# Generated by Django 6.0.3 on 2026-03-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "timetable",
            "0002_alter_room_form_uuid_alter_timetablerule_form_uuid_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="timetablerule",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="timetableslot",
            name="created_by",
        ),
    ]
