# Generated by Django 5.0.3 on 2026-03-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0002_alter_timetablerule_id_alter_timetableslot_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timetablerule",
            options={
                "verbose_name": "قاعدة جدول",
                "verbose_name_plural": "قواعد الجدول",
            },
        ),
        migrations.AlterModelOptions(
            name="timetableslot",
            options={"verbose_name": "حصة", "verbose_name_plural": "الحصص"},
        ),
    ]
