# Generated by Django 6.0.3 on 2026-03-13 03:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="معرّف السجل",
                    ),
                ),
                (
                    "school_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="معرّف المدرسة"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="السنة الأكاديمية",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="الفصل الدراسي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("final", "نهائي"),
                            ("archived", "مؤرشف"),
                        ],
                        default="draft",
                        max_length=24,
                        verbose_name="حالة السجل",
                    ),
                ),
                (
                    "plate",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="رقم اللوحة"
                    ),
                ),
                (
                    "capacity",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="السعة"
                    ),
                ),
                (
                    "gps_enabled",
                    models.BooleanField(default=True, verbose_name="GPS مفعّل"),
                ),
                (
                    "cctv_enabled",
                    models.BooleanField(default=True, verbose_name="كاميرا مفعّلة"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منشئ السجل",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="معرّف السجل",
                    ),
                ),
                (
                    "school_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="معرّف المدرسة"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="السنة الأكاديمية",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="الفصل الدراسي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("final", "نهائي"),
                            ("archived", "مؤرشف"),
                        ],
                        default="draft",
                        max_length=24,
                        verbose_name="حالة السجل",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="اسم المسار")),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.bus",
                        verbose_name="الحافلة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منشئ السجل",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RideLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="معرّف السجل",
                    ),
                ),
                (
                    "school_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="معرّف المدرسة"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="السنة الأكاديمية",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="الفصل الدراسي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("final", "نهائي"),
                            ("archived", "مؤرشف"),
                        ],
                        default="draft",
                        max_length=24,
                        verbose_name="حالة السجل",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="التاريخ")),
                (
                    "boarded",
                    models.SmallIntegerField(default=0, verbose_name="عدد الطلاب"),
                ),
                (
                    "safety_check_pre",
                    models.BooleanField(
                        default=False, verbose_name="فحص السلامة (قبل)"
                    ),
                ),
                (
                    "safety_check_post",
                    models.BooleanField(
                        default=False, verbose_name="فحص السلامة (بعد)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منشئ السجل",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.route",
                        verbose_name="المسار",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DelayLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="معرّف السجل",
                    ),
                ),
                (
                    "school_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="معرّف المدرسة"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="السنة الأكاديمية",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="الفصل الدراسي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("final", "نهائي"),
                            ("archived", "مؤرشف"),
                        ],
                        default="draft",
                        max_length=24,
                        verbose_name="حالة السجل",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="التاريخ")),
                (
                    "arrival_time",
                    models.TimeField(blank=True, null=True, verbose_name="وقت الوصول"),
                ),
                (
                    "delay_minutes",
                    models.SmallIntegerField(default=0, verbose_name="دقائق التأخير"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منشئ السجل",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.route",
                        verbose_name="المسار",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="معرّف السجل",
                    ),
                ),
                (
                    "school_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="معرّف المدرسة"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="السنة الأكاديمية",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="الفصل الدراسي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("final", "نهائي"),
                            ("archived", "مؤرشف"),
                        ],
                        default="draft",
                        max_length=24,
                        verbose_name="حالة السجل",
                    ),
                ),
                ("seq", models.SmallIntegerField(verbose_name="ترتيب الوقفة")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="الموقع"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منشئ السجل",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.route",
                        verbose_name="المسار",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StudentRider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="معرّف السجل",
                    ),
                ),
                (
                    "school_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="معرّف المدرسة"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="السنة الأكاديمية",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="الفصل الدراسي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("final", "نهائي"),
                            ("archived", "مؤرشف"),
                        ],
                        default="draft",
                        max_length=24,
                        verbose_name="حالة السجل",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منشئ السجل",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.route",
                        verbose_name="المسار",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transport.routestop",
                        verbose_name="نقطة الوقوف",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
