# Generated by Django 6.0.3 on 2026-03-12 22:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school_id", models.UUIDField()),
                ("academic_year", models.CharField(max_length=9)),
                ("term", models.CharField(max_length=8)),
                ("form_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_by", models.UUIDField()),
                ("status", models.CharField(default="draft", max_length=24)),
                ("bus_number", models.CharField(max_length=16, unique=True)),
                ("capacity", models.SmallIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school_id", models.UUIDField()),
                ("academic_year", models.CharField(max_length=9)),
                ("term", models.CharField(max_length=8)),
                ("form_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_by", models.UUIDField()),
                ("status", models.CharField(default="draft", max_length=24)),
                ("route_name", models.CharField(max_length=64)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="transport.bus"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school_id", models.UUIDField()),
                ("academic_year", models.CharField(max_length=9)),
                ("term", models.CharField(max_length=8)),
                ("form_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_by", models.UUIDField()),
                ("status", models.CharField(default="draft", max_length=24)),
                ("stop_name", models.CharField(max_length=128)),
                ("order", models.SmallIntegerField()),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.route",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StudentRider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school_id", models.UUIDField()),
                ("academic_year", models.CharField(max_length=9)),
                ("term", models.CharField(max_length=8)),
                ("form_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_by", models.UUIDField()),
                ("status", models.CharField(default="draft", max_length=24)),
                ("assigned_at", models.DateTimeField()),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.route",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RideLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school_id", models.UUIDField()),
                ("academic_year", models.CharField(max_length=9)),
                ("term", models.CharField(max_length=8)),
                ("form_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_by", models.UUIDField()),
                ("log_time", models.DateTimeField()),
                ("status", models.CharField(max_length=24)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.route",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.studentrider",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
