# Generated by Django 6.0.3 on 2026-03-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0002_alter_bus_form_uuid_alter_delaylog_form_uuid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="delaylog",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="ridelog",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="route",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="routestop",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="studentrider",
            name="created_by",
        ),
    ]
