# Generated by Django 6.0.3 on 2026-03-13 03:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="معرّف السجل",
                    ),
                ),
                (
                    "school_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="معرّف المدرسة"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="السنة الأكاديمية",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="الفصل الدراسي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "period",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="الحصة"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "حضور"),
                            ("A", "غياب"),
                            ("E", "عذر"),
                            ("L", "تأخر"),
                            ("ED", "انصراف مبكر"),
                        ],
                        max_length=2,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="رمز السبب"
                    ),
                ),
                ("archived", models.BooleanField(default=False, verbose_name="مؤرشف")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منشئ السجل",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.enrollment",
                        verbose_name="قيد الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل الحضور",
                "verbose_name_plural": "سجلات الحضور",
                "unique_together": {("enrollment", "date", "period")},
            },
        ),
    ]
