# Generated by Django 6.0.3 on 2026-03-12 22:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school_id", models.UUIDField()),
                ("academic_year", models.CharField(max_length=9)),
                ("term", models.CharField(max_length=8)),
                ("form_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_by", models.UUIDField()),
                ("date", models.DateField()),
                ("status", models.CharField(max_length=24)),
                ("arrival_time", models.TimeField(blank=True, null=True)),
                ("minutes_late", models.SmallIntegerField(blank=True, null=True)),
                ("action", models.CharField(blank=True, max_length=64, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "guardian_id_doc",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "evidence_doc_ref",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
