# Generated by Django 6.0.3 on 2026-03-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_attendancerecord_form_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancerecord",
            name="created_by",
        ),
    ]
