# Generated by Django 5.1 on 2026-03-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LookupAbsenceReason",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name_ar", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="LookupNationality",
            fields=[
                (
                    "code",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("name_ar", models.CharField(max_length=120)),
                ("name_en", models.CharField(blank=True, default="", max_length=120)),
            ],
        ),
    ]
