# Generated by Django 5.0.3 on 2026-03-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("refdata", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lookupabsencereason",
            options={"verbose_name": "سبب غياب", "verbose_name_plural": "أسباب الغياب"},
        ),
        migrations.AlterModelOptions(
            name="lookupnationality",
            options={"verbose_name": "جنسية", "verbose_name_plural": "الجنسيات"},
        ),
    ]
