# Generated by Django 5.1 on 2026-03-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BehaviorIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("period", models.SmallIntegerField(blank=True, null=True)),
                ("place", models.CharField(blank=True, default="", max_length=120)),
                ("category", models.CharField(max_length=80)),
                ("description", models.TextField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="people.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BehaviorCommittee",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("members", models.TextField()),
                ("minutes", models.TextField(blank=True, default="")),
                (
                    "incident",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="behavior.behaviorincident",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BehaviorSanction",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("sanction_type", models.CharField(max_length=120)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="behavior.behaviorincident",
                    ),
                ),
            ],
        ),
    ]
