# Generated by Django 5.0.3 on 2026-03-14 18:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("behavior", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="behaviorsanction",
            name="incident",
        ),
        migrations.AlterField(
            model_name="behaviorincident",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.DeleteModel(
            name="BehaviorCommittee",
        ),
        migrations.DeleteModel(
            name="BehaviorSanction",
        ),
    ]
