# Generated by Django 5.0.3 on 2026-03-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("behavior", "0002_remove_behaviorsanction_incident_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="behaviorincident",
            options={
                "verbose_name": "واقعة سلوكية",
                "verbose_name_plural": "وقائع سلوكية",
            },
        ),
    ]
