# Generated by Django 5.1 on 2026-03-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("first_name_ar", models.CharField(max_length=100)),
                ("last_name_ar", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=32)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("first_name_ar", models.CharField(max_length=100)),
                ("last_name_ar", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("first_name_ar", models.CharField(max_length=100)),
                ("last_name_ar", models.CharField(max_length=100)),
                (
                    "first_name_en",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "last_name_en",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("national_id", models.CharField(blank=True, max_length=32, null=True)),
                ("birth_date", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "ذكر"), ("F", "أنثى")], max_length=1
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("grade", models.SmallIntegerField()),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "class_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.classroom"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.school"
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.year"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="people.student"
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("student", "school", "year", "grade", "class_room")
                },
            },
        ),
        migrations.CreateModel(
            name="StudentGuardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relation", models.CharField(max_length=30)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.guardian",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="people.student"
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "guardian")},
            },
        ),
        migrations.CreateModel(
            name="TeachingAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.classroom"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.subject"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="people.staff"
                    ),
                ),
            ],
            options={
                "unique_together": {("teacher", "class_room", "subject")},
            },
        ),
    ]
