# Generated by Django 5.0.3 on 2026-03-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "people",
            "0002_alter_enrollment_id_alter_guardian_id_alter_staff_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollment",
            options={"verbose_name": "قيد طالب", "verbose_name_plural": "قيود الطلبة"},
        ),
        migrations.AlterModelOptions(
            name="guardian",
            options={"verbose_name": "ولي أمر", "verbose_name_plural": "أولياء الأمور"},
        ),
        migrations.AlterModelOptions(
            name="staff",
            options={
                "verbose_name": "موظف/معلم",
                "verbose_name_plural": "الموظفون/المعلمون",
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "طالب", "verbose_name_plural": "الطلبة"},
        ),
        migrations.AlterModelOptions(
            name="studentguardian",
            options={
                "verbose_name": "ربط طالب بولي الأمر",
                "verbose_name_plural": "روابط الطلبة بأولياء الأمور",
            },
        ),
        migrations.AlterModelOptions(
            name="teachingassignment",
            options={
                "verbose_name": "تكليف تدريسي",
                "verbose_name_plural": "التكاليف التدريسية",
            },
        ),
    ]
