# Generated by Django 5.1 on 2026-03-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("capacity", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="DelayLog",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.route",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RideLog",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("departed_at", models.TimeField(blank=True, null=True)),
                ("arrived_at", models.TimeField(blank=True, null=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.route",
                    ),
                ),
            ],
            options={
                "unique_together": {("route", "date")},
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("seq", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.route",
                    ),
                ),
            ],
            options={
                "unique_together": {("route", "seq")},
            },
        ),
        migrations.CreateModel(
            name="StudentRider",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.route",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="people.student"
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "route")},
            },
        ),
    ]
