# Generated by Django 5.0.3 on 2026-03-14 18:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ridelog",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="ridelog",
            name="route",
        ),
        migrations.AlterUniqueTogether(
            name="routestop",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="routestop",
            name="route",
        ),
        migrations.AlterField(
            model_name="route",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="studentrider",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.DeleteModel(
            name="DelayLog",
        ),
        migrations.DeleteModel(
            name="RideLog",
        ),
        migrations.DeleteModel(
            name="RouteStop",
        ),
    ]
