# Generated by Django 5.0.3 on 2026-03-14 19:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transport",
            "0002_alter_ridelog_unique_together_remove_ridelog_route_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="route",
            options={"verbose_name": "مسار نقل", "verbose_name_plural": "مسارات النقل"},
        ),
        migrations.AlterModelOptions(
            name="studentrider",
            options={
                "verbose_name": "مستقل حافلة",
                "verbose_name_plural": "مستقلو الحافلات",
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("seq", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "محطة",
                "verbose_name_plural": "محطات",
                "unique_together": {("route", "seq")},
            },
        ),
    ]
