# Generated by Django 5.0.3 on 2026-03-14 19:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessment",
            "0002_alter_appeal_id_alter_exam_id_alter_examresult_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appeal",
            options={"verbose_name": "تظلّم", "verbose_name_plural": "التظلّمات"},
        ),
        migrations.AlterModelOptions(
            name="exam",
            options={"verbose_name": "اختبار", "verbose_name_plural": "اختبارات"},
        ),
        migrations.AlterModelOptions(
            name="examresult",
            options={
                "verbose_name": "نتيجة اختبار",
                "verbose_name_plural": "نتائج الاختبارات",
            },
        ),
        migrations.CreateModel(
            name="ExamSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment.exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسة اختبار",
                "verbose_name_plural": "جلسات الاختبار",
            },
        ),
    ]
