-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.academics_classroom DROP CONSTRAINT IF EXISTS academics_classroom_school_id_70797bc7_fk_students_school_id;

ALTER TABLE IF EXISTS public.academics_classroom DROP CONSTRAINT IF EXISTS academics_classroom_year_id_54aff3b2_fk_students_;

ALTER TABLE IF EXISTS public.academics_teacher DROP CONSTRAINT IF EXISTS academics_teacher_subject_id_03df8873_fk_academics_subject_id;

ALTER TABLE IF EXISTS public.academics_teachingassignment DROP CONSTRAINT IF EXISTS academics_teachingas_class_room_id_0cea7e50_fk_academics;

ALTER TABLE IF EXISTS public.academics_teachingassignment DROP CONSTRAINT IF EXISTS academics_teachingas_subject_id_609524f1_fk_academics;

ALTER TABLE IF EXISTS public.academics_teachingassignment DROP CONSTRAINT IF EXISTS academics_teachingas_teacher_id_de089ac2_fk_academics;

ALTER TABLE IF EXISTS public.accounts_grouppermission DROP CONSTRAINT IF EXISTS accounts_grouppermis_permission_id_5f6aeb07_fk_accounts_;

ALTER TABLE IF EXISTS public.accounts_grouppermission DROP CONSTRAINT IF EXISTS accounts_grouppermission_group_id_51d4c974_fk_accounts_group_id;

ALTER TABLE IF EXISTS public.accounts_usergroup DROP CONSTRAINT IF EXISTS accounts_usergroup_group_id_4f5e17f4_fk_accounts_group_id;

ALTER TABLE IF EXISTS public.accounts_usergroup DROP CONSTRAINT IF EXISTS accounts_usergroup_user_id_e44e9346_fk_accounts_user_id;

ALTER TABLE IF EXISTS public.assessments_exam DROP CONSTRAINT IF EXISTS assessments_exam_subject_id_fdf4b9b8_fk_academics_subject_id;

ALTER TABLE IF EXISTS public.assessments_exam DROP CONSTRAINT IF EXISTS assessments_exam_term_id_2ad41269_fk_students_term_id;

ALTER TABLE IF EXISTS public.assessments_examresult DROP CONSTRAINT IF EXISTS assessments_examresu_enrollment_id_1b1266dd_fk_students_;

ALTER TABLE IF EXISTS public.assessments_examresult DROP CONSTRAINT IF EXISTS assessments_examresult_exam_id_1fbb7ef0_fk_assessments_exam_id;

ALTER TABLE IF EXISTS public.assessments_examsession DROP CONSTRAINT IF EXISTS assessments_examsession_exam_id_b78ea347_fk_assessments_exam_id;

ALTER TABLE IF EXISTS public.attendance_attendancerecord DROP CONSTRAINT IF EXISTS attendance_attendanc_student_id_d242c468_fk_students_;

ALTER TABLE IF EXISTS public.auth_group_permissions DROP CONSTRAINT IF EXISTS auth_group_permissio_permission_id_84c5c92e_fk_auth_perm;

ALTER TABLE IF EXISTS public.auth_group_permissions DROP CONSTRAINT IF EXISTS auth_group_permissions_group_id_b120cbf9_fk_auth_group_id;

ALTER TABLE IF EXISTS public.auth_permission DROP CONSTRAINT IF EXISTS auth_permission_content_type_id_2f476e4b_fk_django_co;

ALTER TABLE IF EXISTS public.auth_user_groups DROP CONSTRAINT IF EXISTS auth_user_groups_group_id_97559544_fk_auth_group_id;

ALTER TABLE IF EXISTS public.auth_user_groups DROP CONSTRAINT IF EXISTS auth_user_groups_user_id_6a12ed8b_fk_auth_user_id;

ALTER TABLE IF EXISTS public.auth_user_user_permissions DROP CONSTRAINT IF EXISTS auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm;

ALTER TABLE IF EXISTS public.auth_user_user_permissions DROP CONSTRAINT IF EXISTS auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id;

ALTER TABLE IF EXISTS public.behavior_behaviorcommittee DROP CONSTRAINT IF EXISTS behavior_behaviorcom_incident_id_601ffb27_fk_behavior_;

ALTER TABLE IF EXISTS public.behavior_behaviorincident DROP CONSTRAINT IF EXISTS behavior_behaviorinc_offense_code_id_5bb40b96_fk_behavior_;

ALTER TABLE IF EXISTS public.behavior_behaviorincident DROP CONSTRAINT IF EXISTS behavior_behaviorinc_student_id_ba9304c0_fk_students_;

ALTER TABLE IF EXISTS public.behavior_behaviorsanction DROP CONSTRAINT IF EXISTS behavior_behaviorsan_incident_id_4bb70e5a_fk_behavior_;

ALTER TABLE IF EXISTS public.django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_content_type_id_c4bce8eb_fk_django_co;

ALTER TABLE IF EXISTS public.django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_user_id_c564eba6_fk_auth_user_id;

ALTER TABLE IF EXISTS public.health_clinicvisit DROP CONSTRAINT IF EXISTS health_clinicvisit_student_id_01fa7a27_fk_students_student_id;

ALTER TABLE IF EXISTS public.health_medicationlog DROP CONSTRAINT IF EXISTS health_medicationlog_clinic_visit_id_464a4533_fk_health_cl;

ALTER TABLE IF EXISTS public.hr_disciplinaryaction DROP CONSTRAINT IF EXISTS hr_disciplinaryaction_staff_id_c6b3461b_fk_hr_staff_id;

ALTER TABLE IF EXISTS public.hr_leaverequest DROP CONSTRAINT IF EXISTS hr_leaverequest_staff_id_d6303926_fk_hr_staff_id;

ALTER TABLE IF EXISTS public.hr_performancereview DROP CONSTRAINT IF EXISTS hr_performancereview_staff_id_e19a3a73_fk_hr_staff_id;

ALTER TABLE IF EXISTS public.hr_staffattendance DROP CONSTRAINT IF EXISTS hr_staffattendance_staff_id_ce83fd8d_fk_hr_staff_id;

ALTER TABLE IF EXISTS public.library_librarycopy DROP CONSTRAINT IF EXISTS library_librarycopy_title_id_58c47120_fk_library_l;

ALTER TABLE IF EXISTS public.library_libraryloan DROP CONSTRAINT IF EXISTS library_libraryloan_copy_id_6bfd4429_fk_library_librarycopy_id;

ALTER TABLE IF EXISTS public.notifications_notice DROP CONSTRAINT IF EXISTS notifications_notice_student_id_cd3f6255_fk_students_student_id;

ALTER TABLE IF EXISTS public.quality_qualityevidence DROP CONSTRAINT IF EXISTS quality_qualityevide_indicator_id_3038dff0_fk_quality_q;

ALTER TABLE IF EXISTS public.quality_qualityindicator DROP CONSTRAINT IF EXISTS quality_qualityindic_standard_id_3a10fc34_fk_quality_q;

ALTER TABLE IF EXISTS public.students_enrollment DROP CONSTRAINT IF EXISTS students_enrollment_school_id_02177b40_fk_students_school_id;

ALTER TABLE IF EXISTS public.students_enrollment DROP CONSTRAINT IF EXISTS students_enrollment_student_id_f38f10af_fk_students_student_id;

ALTER TABLE IF EXISTS public.students_enrollment DROP CONSTRAINT IF EXISTS students_enrollment_year_id_93fdf14a_fk_students_;

ALTER TABLE IF EXISTS public.students_student DROP CONSTRAINT IF EXISTS students_student_guardian_id_2bea6c4b_fk_students_guardian_id;

ALTER TABLE IF EXISTS public.students_term DROP CONSTRAINT IF EXISTS students_term_year_id_8daf548d_fk_students_academicyear_id;

ALTER TABLE IF EXISTS public.timetable_timetableslot DROP CONSTRAINT IF EXISTS timetable_timetables_class_room_id_5b9f8846_fk_academics;

ALTER TABLE IF EXISTS public.timetable_timetableslot DROP CONSTRAINT IF EXISTS timetable_timetables_subject_id_418a7e92_fk_academics;

ALTER TABLE IF EXISTS public.timetable_timetableslot DROP CONSTRAINT IF EXISTS timetable_timetables_teacher_id_783644e6_fk_academics;

ALTER TABLE IF EXISTS public.transport_ridelog DROP CONSTRAINT IF EXISTS transport_ridelog_rider_id_0abfa4e9_fk_transport;

ALTER TABLE IF EXISTS public.transport_ridelog DROP CONSTRAINT IF EXISTS transport_ridelog_route_id_181266b1_fk_transport_route_id;

ALTER TABLE IF EXISTS public.transport_route DROP CONSTRAINT IF EXISTS transport_route_bus_id_1afbcbd5_fk_transport_bus_id;

ALTER TABLE IF EXISTS public.transport_routestop DROP CONSTRAINT IF EXISTS transport_routestop_route_id_ccb3f331_fk_transport_route_id;

ALTER TABLE IF EXISTS public.transport_studentrider DROP CONSTRAINT IF EXISTS transport_studentrid_student_id_c914bca2_fk_students_;

ALTER TABLE IF EXISTS public.transport_studentrider DROP CONSTRAINT IF EXISTS transport_studentrider_route_id_62d017c2_fk_transport_route_id;



DROP TABLE IF EXISTS public.academics_classroom;

CREATE TABLE IF NOT EXISTS public.academics_classroom
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    grade character varying(16) COLLATE pg_catalog."default" NOT NULL,
    section character varying(8) COLLATE pg_catalog."default" NOT NULL,
    capacity smallint,
    school_id uuid NOT NULL,
    year_id uuid NOT NULL,
    CONSTRAINT academics_classroom_pkey PRIMARY KEY (id),
    CONSTRAINT academics_classroom_school_id_year_id_grade__3e49a888_uniq UNIQUE (school_id, year_id, grade, section)
);

DROP TABLE IF EXISTS public.academics_subject;

CREATE TABLE IF NOT EXISTS public.academics_subject
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    code character varying(32) COLLATE pg_catalog."default" NOT NULL,
    name_ar character varying(128) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT academics_subject_pkey PRIMARY KEY (id),
    CONSTRAINT academics_subject_code_key UNIQUE (code)
);

DROP TABLE IF EXISTS public.academics_teacher;

CREATE TABLE IF NOT EXISTS public.academics_teacher
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    full_name_ar character varying(128) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(32) COLLATE pg_catalog."default",
    subject_id uuid,
    CONSTRAINT academics_teacher_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.academics_teachingassignment;

CREATE TABLE IF NOT EXISTS public.academics_teachingassignment
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    class_room_id uuid NOT NULL,
    subject_id uuid NOT NULL,
    teacher_id uuid NOT NULL,
    CONSTRAINT academics_teachingassignment_pkey PRIMARY KEY (id),
    CONSTRAINT academics_teachingassign_teacher_id_subject_id_cl_e9f846aa_uniq UNIQUE (teacher_id, subject_id, class_room_id)
);

DROP TABLE IF EXISTS public.accounts_group;

CREATE TABLE IF NOT EXISTS public.accounts_group
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    name character varying(64) COLLATE pg_catalog."default" NOT NULL,
    description character varying(256) COLLATE pg_catalog."default",
    CONSTRAINT accounts_group_pkey PRIMARY KEY (id),
    CONSTRAINT accounts_group_name_key UNIQUE (name)
);

DROP TABLE IF EXISTS public.accounts_grouppermission;

CREATE TABLE IF NOT EXISTS public.accounts_grouppermission
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    group_id uuid NOT NULL,
    permission_id uuid NOT NULL,
    CONSTRAINT accounts_grouppermission_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.accounts_permission;

CREATE TABLE IF NOT EXISTS public.accounts_permission
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    code character varying(64) COLLATE pg_catalog."default" NOT NULL,
    description character varying(256) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT accounts_permission_pkey PRIMARY KEY (id),
    CONSTRAINT accounts_permission_code_key UNIQUE (code)
);

DROP TABLE IF EXISTS public.accounts_user;

CREATE TABLE IF NOT EXISTS public.accounts_user
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    username character varying(64) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    is_superuser boolean NOT NULL,
    CONSTRAINT accounts_user_pkey PRIMARY KEY (id),
    CONSTRAINT accounts_user_email_key UNIQUE (email),
    CONSTRAINT accounts_user_username_key UNIQUE (username)
);

DROP TABLE IF EXISTS public.accounts_usergroup;

CREATE TABLE IF NOT EXISTS public.accounts_usergroup
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    group_id uuid NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT accounts_usergroup_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.assessments_exam;

CREATE TABLE IF NOT EXISTS public.assessments_exam
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    exam_type character varying(32) COLLATE pg_catalog."default" NOT NULL,
    date date NOT NULL,
    subject_id uuid NOT NULL,
    term_id uuid NOT NULL,
    CONSTRAINT assessments_exam_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.assessments_examresult;

CREATE TABLE IF NOT EXISTS public.assessments_examresult
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    score numeric(5, 2) NOT NULL,
    grade character varying(16) COLLATE pg_catalog."default" NOT NULL,
    enrollment_id uuid NOT NULL,
    exam_id uuid NOT NULL,
    CONSTRAINT assessments_examresult_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.assessments_examsession;

CREATE TABLE IF NOT EXISTS public.assessments_examsession
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    scheduled_at timestamp with time zone NOT NULL,
    room character varying(64) COLLATE pg_catalog."default" NOT NULL,
    exam_id uuid NOT NULL,
    CONSTRAINT assessments_examsession_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.attendance_attendancerecord;

CREATE TABLE IF NOT EXISTS public.attendance_attendancerecord
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    date date NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    arrival_time time without time zone,
    minutes_late smallint,
    action character varying(64) COLLATE pg_catalog."default",
    reason text COLLATE pg_catalog."default",
    guardian_id_doc character varying(64) COLLATE pg_catalog."default",
    evidence_doc_ref character varying(256) COLLATE pg_catalog."default",
    student_id uuid NOT NULL,
    CONSTRAINT attendance_attendancerecord_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.audit_auditlog;

CREATE TABLE IF NOT EXISTS public.audit_auditlog
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    user_id uuid NOT NULL,
    action character varying(64) COLLATE pg_catalog."default" NOT NULL,
    target character varying(128) COLLATE pg_catalog."default" NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    details text COLLATE pg_catalog."default",
    CONSTRAINT audit_auditlog_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.auth_group;

CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

DROP TABLE IF EXISTS public.auth_group_permissions;

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

DROP TABLE IF EXISTS public.auth_permission;

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

DROP TABLE IF EXISTS public.auth_user;

CREATE TABLE IF NOT EXISTS public.auth_user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    CONSTRAINT auth_user_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_username_key UNIQUE (username)
);

DROP TABLE IF EXISTS public.auth_user_groups;

CREATE TABLE IF NOT EXISTS public.auth_user_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id)
);

DROP TABLE IF EXISTS public.auth_user_user_permissions;

CREATE TABLE IF NOT EXISTS public.auth_user_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id)
);

DROP TABLE IF EXISTS public.behavior_behaviorcommittee;

CREATE TABLE IF NOT EXISTS public.behavior_behaviorcommittee
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    decision text COLLATE pg_catalog."default" NOT NULL,
    members text COLLATE pg_catalog."default" NOT NULL,
    incident_id uuid NOT NULL,
    CONSTRAINT behavior_behaviorcommittee_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.behavior_behaviorincident;

CREATE TABLE IF NOT EXISTS public.behavior_behaviorincident
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    date timestamp with time zone NOT NULL,
    reporter_id uuid,
    narrative text COLLATE pg_catalog."default",
    evidence_ref character varying(256) COLLATE pg_catalog."default",
    student_id uuid NOT NULL,
    offense_code_id uuid NOT NULL,
    CONSTRAINT behavior_behaviorincident_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.behavior_behaviorsanction;

CREATE TABLE IF NOT EXISTS public.behavior_behaviorsanction
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    sanction_type character varying(64) COLLATE pg_catalog."default" NOT NULL,
    details text COLLATE pg_catalog."default",
    incident_id uuid NOT NULL,
    CONSTRAINT behavior_behaviorsanction_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.behavior_offensecode;

CREATE TABLE IF NOT EXISTS public.behavior_offensecode
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    code character varying(16) COLLATE pg_catalog."default" NOT NULL,
    description character varying(256) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT behavior_offensecode_pkey PRIMARY KEY (id),
    CONSTRAINT behavior_offensecode_code_key UNIQUE (code)
);

DROP TABLE IF EXISTS public.django_admin_log;

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.django_content_type;

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

DROP TABLE IF EXISTS public.django_migrations;

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.django_session;

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

DROP TABLE IF EXISTS public.health_clinicvisit;

CREATE TABLE IF NOT EXISTS public.health_clinicvisit
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    visit_date date NOT NULL,
    medical_note bytea,
    student_id uuid NOT NULL,
    CONSTRAINT health_clinicvisit_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.health_medicationlog;

CREATE TABLE IF NOT EXISTS public.health_medicationlog
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    medication_name character varying(128) COLLATE pg_catalog."default" NOT NULL,
    dose character varying(64) COLLATE pg_catalog."default" NOT NULL,
    issued_at timestamp with time zone NOT NULL,
    clinic_visit_id uuid NOT NULL,
    CONSTRAINT health_medicationlog_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.hr_disciplinaryaction;

CREATE TABLE IF NOT EXISTS public.hr_disciplinaryaction
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    action_type character varying(64) COLLATE pg_catalog."default" NOT NULL,
    details text COLLATE pg_catalog."default",
    staff_id uuid NOT NULL,
    CONSTRAINT hr_disciplinaryaction_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.hr_leaverequest;

CREATE TABLE IF NOT EXISTS public.hr_leaverequest
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    leave_type character varying(32) COLLATE pg_catalog."default" NOT NULL,
    from_date date NOT NULL,
    to_date date NOT NULL,
    reason text COLLATE pg_catalog."default",
    staff_id uuid NOT NULL,
    CONSTRAINT hr_leaverequest_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.hr_performancereview;

CREATE TABLE IF NOT EXISTS public.hr_performancereview
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    reviewer_id uuid NOT NULL,
    review_date date NOT NULL,
    score numeric(5, 2) NOT NULL,
    notes text COLLATE pg_catalog."default",
    staff_id uuid NOT NULL,
    CONSTRAINT hr_performancereview_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.hr_staff;

CREATE TABLE IF NOT EXISTS public.hr_staff
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    full_name_ar character varying(128) COLLATE pg_catalog."default" NOT NULL,
    "position" character varying(64) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(32) COLLATE pg_catalog."default",
    CONSTRAINT hr_staff_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.hr_staffattendance;

CREATE TABLE IF NOT EXISTS public.hr_staffattendance
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    date date NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    staff_id uuid NOT NULL,
    CONSTRAINT hr_staffattendance_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.library_librarycopy;

CREATE TABLE IF NOT EXISTS public.library_librarycopy
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    copy_number character varying(16) COLLATE pg_catalog."default" NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    title_id uuid NOT NULL,
    CONSTRAINT library_librarycopy_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.library_libraryloan;

CREATE TABLE IF NOT EXISTS public.library_libraryloan
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    borrower_id uuid NOT NULL,
    loan_date date NOT NULL,
    return_date date,
    copy_id uuid NOT NULL,
    CONSTRAINT library_libraryloan_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.library_librarytitle;

CREATE TABLE IF NOT EXISTS public.library_librarytitle
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    title character varying(256) COLLATE pg_catalog."default" NOT NULL,
    author character varying(128) COLLATE pg_catalog."default" NOT NULL,
    isbn character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT library_librarytitle_pkey PRIMARY KEY (id),
    CONSTRAINT library_librarytitle_isbn_key UNIQUE (isbn)
);

DROP TABLE IF EXISTS public.notifications_notice;

CREATE TABLE IF NOT EXISTS public.notifications_notice
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    sent_at timestamp with time zone NOT NULL,
    channel character varying(32) COLLATE pg_catalog."default" NOT NULL,
    student_id uuid NOT NULL,
    CONSTRAINT notifications_notice_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.quality_qualityevidence;

CREATE TABLE IF NOT EXISTS public.quality_qualityevidence
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    evidence character varying(256) COLLATE pg_catalog."default" NOT NULL,
    file_ref character varying(256) COLLATE pg_catalog."default",
    indicator_id uuid NOT NULL,
    CONSTRAINT quality_qualityevidence_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.quality_qualityindicator;

CREATE TABLE IF NOT EXISTS public.quality_qualityindicator
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    indicator character varying(128) COLLATE pg_catalog."default" NOT NULL,
    standard_id uuid NOT NULL,
    CONSTRAINT quality_qualityindicator_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.quality_qualitystandard;

CREATE TABLE IF NOT EXISTS public.quality_qualitystandard
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    code character varying(32) COLLATE pg_catalog."default" NOT NULL,
    description character varying(256) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT quality_qualitystandard_pkey PRIMARY KEY (id),
    CONSTRAINT quality_qualitystandard_code_key UNIQUE (code)
);

DROP TABLE IF EXISTS public.students_academicyear;

CREATE TABLE IF NOT EXISTS public.students_academicyear
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    code character varying(9) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT students_academicyear_pkey PRIMARY KEY (id),
    CONSTRAINT students_academicyear_code_key UNIQUE (code)
);

DROP TABLE IF EXISTS public.students_enrollment;

CREATE TABLE IF NOT EXISTS public.students_enrollment
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    grade character varying(16) COLLATE pg_catalog."default" NOT NULL,
    section character varying(8) COLLATE pg_catalog."default",
    valid_from date NOT NULL,
    valid_to date,
    year_id uuid NOT NULL,
    school_id uuid NOT NULL,
    student_id uuid NOT NULL,
    CONSTRAINT students_enrollment_pkey PRIMARY KEY (id),
    CONSTRAINT students_enrollment_student_id_school_id_yea_a18d2b99_uniq UNIQUE (student_id, school_id, year_id, grade, section)
);

DROP TABLE IF EXISTS public.students_guardian;

CREATE TABLE IF NOT EXISTS public.students_guardian
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    full_name_ar character varying(128) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(32) COLLATE pg_catalog."default" NOT NULL,
    relation character varying(32) COLLATE pg_catalog."default",
    CONSTRAINT students_guardian_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.students_school;

CREATE TABLE IF NOT EXISTS public.students_school
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    name_ar character varying(256) COLLATE pg_catalog."default" NOT NULL,
    moe_code character varying(32) COLLATE pg_catalog."default",
    level character varying(32) COLLATE pg_catalog."default",
    CONSTRAINT students_school_pkey PRIMARY KEY (id),
    CONSTRAINT students_school_moe_code_key UNIQUE (moe_code)
);

DROP TABLE IF EXISTS public.students_student;

CREATE TABLE IF NOT EXISTS public.students_student
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    national_id character varying(32) COLLATE pg_catalog."default" NOT NULL,
    first_name_ar character varying(64) COLLATE pg_catalog."default" NOT NULL,
    last_name_ar character varying(64) COLLATE pg_catalog."default" NOT NULL,
    dob date NOT NULL,
    nationality character varying(64) COLLATE pg_catalog."default",
    pdppl_guardian_consent boolean NOT NULL,
    consent_ts timestamp with time zone,
    guardian_id uuid,
    CONSTRAINT students_student_pkey PRIMARY KEY (id),
    CONSTRAINT students_student_national_id_key UNIQUE (national_id)
);

DROP TABLE IF EXISTS public.students_term;

CREATE TABLE IF NOT EXISTS public.students_term
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    code character varying(8) COLLATE pg_catalog."default" NOT NULL,
    year_id uuid NOT NULL,
    CONSTRAINT students_term_pkey PRIMARY KEY (id),
    CONSTRAINT students_term_year_id_code_8528cc2c_uniq UNIQUE (year_id, code)
);

DROP TABLE IF EXISTS public.timetable_timetablerule;

CREATE TABLE IF NOT EXISTS public.timetable_timetablerule
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    rule_json jsonb NOT NULL,
    CONSTRAINT timetable_timetablerule_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.timetable_timetableslot;

CREATE TABLE IF NOT EXISTS public.timetable_timetableslot
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    slot_time timestamp with time zone NOT NULL,
    room character varying(64) COLLATE pg_catalog."default" NOT NULL,
    class_room_id uuid NOT NULL,
    subject_id uuid NOT NULL,
    teacher_id uuid NOT NULL,
    CONSTRAINT timetable_timetableslot_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.transport_bus;

CREATE TABLE IF NOT EXISTS public.transport_bus
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    bus_number character varying(16) COLLATE pg_catalog."default" NOT NULL,
    capacity smallint NOT NULL,
    CONSTRAINT transport_bus_pkey PRIMARY KEY (id),
    CONSTRAINT transport_bus_bus_number_key UNIQUE (bus_number)
);

DROP TABLE IF EXISTS public.transport_ridelog;

CREATE TABLE IF NOT EXISTS public.transport_ridelog
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    log_time timestamp with time zone NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    route_id uuid NOT NULL,
    rider_id uuid NOT NULL,
    CONSTRAINT transport_ridelog_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.transport_route;

CREATE TABLE IF NOT EXISTS public.transport_route
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    route_name character varying(64) COLLATE pg_catalog."default" NOT NULL,
    bus_id uuid NOT NULL,
    CONSTRAINT transport_route_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.transport_routestop;

CREATE TABLE IF NOT EXISTS public.transport_routestop
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    stop_name character varying(128) COLLATE pg_catalog."default" NOT NULL,
    "order" smallint NOT NULL,
    route_id uuid NOT NULL,
    CONSTRAINT transport_routestop_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.transport_studentrider;

CREATE TABLE IF NOT EXISTS public.transport_studentrider
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id uuid NOT NULL,
    academic_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    term character varying(8) COLLATE pg_catalog."default" NOT NULL,
    form_uuid uuid NOT NULL,
    created_by uuid NOT NULL,
    status character varying(24) COLLATE pg_catalog."default" NOT NULL,
    assigned_at timestamp with time zone NOT NULL,
    route_id uuid NOT NULL,
    student_id uuid NOT NULL,
    CONSTRAINT transport_studentrider_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.academics_classroom
    ADD CONSTRAINT academics_classroom_school_id_70797bc7_fk_students_school_id FOREIGN KEY (school_id)
    REFERENCES public.students_school (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS academics_classroom_school_id_70797bc7
    ON public.academics_classroom(school_id);


ALTER TABLE IF EXISTS public.academics_classroom
    ADD CONSTRAINT academics_classroom_year_id_54aff3b2_fk_students_ FOREIGN KEY (year_id)
    REFERENCES public.students_academicyear (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS academics_classroom_year_id_54aff3b2
    ON public.academics_classroom(year_id);


ALTER TABLE IF EXISTS public.academics_teacher
    ADD CONSTRAINT academics_teacher_subject_id_03df8873_fk_academics_subject_id FOREIGN KEY (subject_id)
    REFERENCES public.academics_subject (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS academics_teacher_subject_id_03df8873
    ON public.academics_teacher(subject_id);


ALTER TABLE IF EXISTS public.academics_teachingassignment
    ADD CONSTRAINT academics_teachingas_class_room_id_0cea7e50_fk_academics FOREIGN KEY (class_room_id)
    REFERENCES public.academics_classroom (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS academics_teachingassignment_class_room_id_0cea7e50
    ON public.academics_teachingassignment(class_room_id);


ALTER TABLE IF EXISTS public.academics_teachingassignment
    ADD CONSTRAINT academics_teachingas_subject_id_609524f1_fk_academics FOREIGN KEY (subject_id)
    REFERENCES public.academics_subject (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS academics_teachingassignment_subject_id_609524f1
    ON public.academics_teachingassignment(subject_id);


ALTER TABLE IF EXISTS public.academics_teachingassignment
    ADD CONSTRAINT academics_teachingas_teacher_id_de089ac2_fk_academics FOREIGN KEY (teacher_id)
    REFERENCES public.academics_teacher (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS academics_teachingassignment_teacher_id_de089ac2
    ON public.academics_teachingassignment(teacher_id);


ALTER TABLE IF EXISTS public.accounts_grouppermission
    ADD CONSTRAINT accounts_grouppermis_permission_id_5f6aeb07_fk_accounts_ FOREIGN KEY (permission_id)
    REFERENCES public.accounts_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS accounts_grouppermission_permission_id_5f6aeb07
    ON public.accounts_grouppermission(permission_id);


ALTER TABLE IF EXISTS public.accounts_grouppermission
    ADD CONSTRAINT accounts_grouppermission_group_id_51d4c974_fk_accounts_group_id FOREIGN KEY (group_id)
    REFERENCES public.accounts_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS accounts_grouppermission_group_id_51d4c974
    ON public.accounts_grouppermission(group_id);


ALTER TABLE IF EXISTS public.accounts_usergroup
    ADD CONSTRAINT accounts_usergroup_group_id_4f5e17f4_fk_accounts_group_id FOREIGN KEY (group_id)
    REFERENCES public.accounts_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS accounts_usergroup_group_id_4f5e17f4
    ON public.accounts_usergroup(group_id);


ALTER TABLE IF EXISTS public.accounts_usergroup
    ADD CONSTRAINT accounts_usergroup_user_id_e44e9346_fk_accounts_user_id FOREIGN KEY (user_id)
    REFERENCES public.accounts_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS accounts_usergroup_user_id_e44e9346
    ON public.accounts_usergroup(user_id);


ALTER TABLE IF EXISTS public.assessments_exam
    ADD CONSTRAINT assessments_exam_subject_id_fdf4b9b8_fk_academics_subject_id FOREIGN KEY (subject_id)
    REFERENCES public.academics_subject (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS assessments_exam_subject_id_fdf4b9b8
    ON public.assessments_exam(subject_id);


ALTER TABLE IF EXISTS public.assessments_exam
    ADD CONSTRAINT assessments_exam_term_id_2ad41269_fk_students_term_id FOREIGN KEY (term_id)
    REFERENCES public.students_term (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS assessments_exam_term_id_2ad41269
    ON public.assessments_exam(term_id);


ALTER TABLE IF EXISTS public.assessments_examresult
    ADD CONSTRAINT assessments_examresu_enrollment_id_1b1266dd_fk_students_ FOREIGN KEY (enrollment_id)
    REFERENCES public.students_enrollment (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS assessments_examresult_enrollment_id_1b1266dd
    ON public.assessments_examresult(enrollment_id);


ALTER TABLE IF EXISTS public.assessments_examresult
    ADD CONSTRAINT assessments_examresult_exam_id_1fbb7ef0_fk_assessments_exam_id FOREIGN KEY (exam_id)
    REFERENCES public.assessments_exam (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS assessments_examresult_exam_id_1fbb7ef0
    ON public.assessments_examresult(exam_id);


ALTER TABLE IF EXISTS public.assessments_examsession
    ADD CONSTRAINT assessments_examsession_exam_id_b78ea347_fk_assessments_exam_id FOREIGN KEY (exam_id)
    REFERENCES public.assessments_exam (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS assessments_examsession_exam_id_b78ea347
    ON public.assessments_examsession(exam_id);


ALTER TABLE IF EXISTS public.attendance_attendancerecord
    ADD CONSTRAINT attendance_attendanc_student_id_d242c468_fk_students_ FOREIGN KEY (student_id)
    REFERENCES public.students_student (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS attendance_attendancerecord_student_id_d242c468
    ON public.attendance_attendancerecord(student_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_group_id_97559544
    ON public.auth_user_groups(group_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_user_id_6a12ed8b
    ON public.auth_user_groups(user_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_permission_id_1fbb5f2c
    ON public.auth_user_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_user_id_a95ead1b
    ON public.auth_user_user_permissions(user_id);


ALTER TABLE IF EXISTS public.behavior_behaviorcommittee
    ADD CONSTRAINT behavior_behaviorcom_incident_id_601ffb27_fk_behavior_ FOREIGN KEY (incident_id)
    REFERENCES public.behavior_behaviorincident (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS behavior_behaviorcommittee_incident_id_601ffb27
    ON public.behavior_behaviorcommittee(incident_id);


ALTER TABLE IF EXISTS public.behavior_behaviorincident
    ADD CONSTRAINT behavior_behaviorinc_offense_code_id_5bb40b96_fk_behavior_ FOREIGN KEY (offense_code_id)
    REFERENCES public.behavior_offensecode (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS behavior_behaviorincident_offense_code_id_5bb40b96
    ON public.behavior_behaviorincident(offense_code_id);


ALTER TABLE IF EXISTS public.behavior_behaviorincident
    ADD CONSTRAINT behavior_behaviorinc_student_id_ba9304c0_fk_students_ FOREIGN KEY (student_id)
    REFERENCES public.students_student (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS behavior_behaviorincident_student_id_ba9304c0
    ON public.behavior_behaviorincident(student_id);


ALTER TABLE IF EXISTS public.behavior_behaviorsanction
    ADD CONSTRAINT behavior_behaviorsan_incident_id_4bb70e5a_fk_behavior_ FOREIGN KEY (incident_id)
    REFERENCES public.behavior_behaviorincident (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS behavior_behaviorsanction_incident_id_4bb70e5a
    ON public.behavior_behaviorsanction(incident_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.health_clinicvisit
    ADD CONSTRAINT health_clinicvisit_student_id_01fa7a27_fk_students_student_id FOREIGN KEY (student_id)
    REFERENCES public.students_student (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS health_clinicvisit_student_id_01fa7a27
    ON public.health_clinicvisit(student_id);


ALTER TABLE IF EXISTS public.health_medicationlog
    ADD CONSTRAINT health_medicationlog_clinic_visit_id_464a4533_fk_health_cl FOREIGN KEY (clinic_visit_id)
    REFERENCES public.health_clinicvisit (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS health_medicationlog_clinic_visit_id_464a4533
    ON public.health_medicationlog(clinic_visit_id);


ALTER TABLE IF EXISTS public.hr_disciplinaryaction
    ADD CONSTRAINT hr_disciplinaryaction_staff_id_c6b3461b_fk_hr_staff_id FOREIGN KEY (staff_id)
    REFERENCES public.hr_staff (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS hr_disciplinaryaction_staff_id_c6b3461b
    ON public.hr_disciplinaryaction(staff_id);


ALTER TABLE IF EXISTS public.hr_leaverequest
    ADD CONSTRAINT hr_leaverequest_staff_id_d6303926_fk_hr_staff_id FOREIGN KEY (staff_id)
    REFERENCES public.hr_staff (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS hr_leaverequest_staff_id_d6303926
    ON public.hr_leaverequest(staff_id);


ALTER TABLE IF EXISTS public.hr_performancereview
    ADD CONSTRAINT hr_performancereview_staff_id_e19a3a73_fk_hr_staff_id FOREIGN KEY (staff_id)
    REFERENCES public.hr_staff (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS hr_performancereview_staff_id_e19a3a73
    ON public.hr_performancereview(staff_id);


ALTER TABLE IF EXISTS public.hr_staffattendance
    ADD CONSTRAINT hr_staffattendance_staff_id_ce83fd8d_fk_hr_staff_id FOREIGN KEY (staff_id)
    REFERENCES public.hr_staff (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS hr_staffattendance_staff_id_ce83fd8d
    ON public.hr_staffattendance(staff_id);


ALTER TABLE IF EXISTS public.library_librarycopy
    ADD CONSTRAINT library_librarycopy_title_id_58c47120_fk_library_l FOREIGN KEY (title_id)
    REFERENCES public.library_librarytitle (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS library_librarycopy_title_id_58c47120
    ON public.library_librarycopy(title_id);


ALTER TABLE IF EXISTS public.library_libraryloan
    ADD CONSTRAINT library_libraryloan_copy_id_6bfd4429_fk_library_librarycopy_id FOREIGN KEY (copy_id)
    REFERENCES public.library_librarycopy (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS library_libraryloan_copy_id_6bfd4429
    ON public.library_libraryloan(copy_id);


ALTER TABLE IF EXISTS public.notifications_notice
    ADD CONSTRAINT notifications_notice_student_id_cd3f6255_fk_students_student_id FOREIGN KEY (student_id)
    REFERENCES public.students_student (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS notifications_notice_student_id_cd3f6255
    ON public.notifications_notice(student_id);


ALTER TABLE IF EXISTS public.quality_qualityevidence
    ADD CONSTRAINT quality_qualityevide_indicator_id_3038dff0_fk_quality_q FOREIGN KEY (indicator_id)
    REFERENCES public.quality_qualityindicator (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS quality_qualityevidence_indicator_id_3038dff0
    ON public.quality_qualityevidence(indicator_id);


ALTER TABLE IF EXISTS public.quality_qualityindicator
    ADD CONSTRAINT quality_qualityindic_standard_id_3a10fc34_fk_quality_q FOREIGN KEY (standard_id)
    REFERENCES public.quality_qualitystandard (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS quality_qualityindicator_standard_id_3a10fc34
    ON public.quality_qualityindicator(standard_id);


ALTER TABLE IF EXISTS public.students_enrollment
    ADD CONSTRAINT students_enrollment_school_id_02177b40_fk_students_school_id FOREIGN KEY (school_id)
    REFERENCES public.students_school (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS students_enrollment_school_id_02177b40
    ON public.students_enrollment(school_id);


ALTER TABLE IF EXISTS public.students_enrollment
    ADD CONSTRAINT students_enrollment_student_id_f38f10af_fk_students_student_id FOREIGN KEY (student_id)
    REFERENCES public.students_student (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS students_enrollment_student_id_f38f10af
    ON public.students_enrollment(student_id);


ALTER TABLE IF EXISTS public.students_enrollment
    ADD CONSTRAINT students_enrollment_year_id_93fdf14a_fk_students_ FOREIGN KEY (year_id)
    REFERENCES public.students_academicyear (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS students_enrollment_year_id_93fdf14a
    ON public.students_enrollment(year_id);


ALTER TABLE IF EXISTS public.students_student
    ADD CONSTRAINT students_student_guardian_id_2bea6c4b_fk_students_guardian_id FOREIGN KEY (guardian_id)
    REFERENCES public.students_guardian (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS students_student_guardian_id_2bea6c4b
    ON public.students_student(guardian_id);


ALTER TABLE IF EXISTS public.students_term
    ADD CONSTRAINT students_term_year_id_8daf548d_fk_students_academicyear_id FOREIGN KEY (year_id)
    REFERENCES public.students_academicyear (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS students_term_year_id_8daf548d
    ON public.students_term(year_id);


ALTER TABLE IF EXISTS public.timetable_timetableslot
    ADD CONSTRAINT timetable_timetables_class_room_id_5b9f8846_fk_academics FOREIGN KEY (class_room_id)
    REFERENCES public.academics_classroom (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS timetable_timetableslot_class_room_id_5b9f8846
    ON public.timetable_timetableslot(class_room_id);


ALTER TABLE IF EXISTS public.timetable_timetableslot
    ADD CONSTRAINT timetable_timetables_subject_id_418a7e92_fk_academics FOREIGN KEY (subject_id)
    REFERENCES public.academics_subject (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS timetable_timetableslot_subject_id_418a7e92
    ON public.timetable_timetableslot(subject_id);


ALTER TABLE IF EXISTS public.timetable_timetableslot
    ADD CONSTRAINT timetable_timetables_teacher_id_783644e6_fk_academics FOREIGN KEY (teacher_id)
    REFERENCES public.academics_teacher (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS timetable_timetableslot_teacher_id_783644e6
    ON public.timetable_timetableslot(teacher_id);


ALTER TABLE IF EXISTS public.transport_ridelog
    ADD CONSTRAINT transport_ridelog_rider_id_0abfa4e9_fk_transport FOREIGN KEY (rider_id)
    REFERENCES public.transport_studentrider (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS transport_ridelog_rider_id_0abfa4e9
    ON public.transport_ridelog(rider_id);


ALTER TABLE IF EXISTS public.transport_ridelog
    ADD CONSTRAINT transport_ridelog_route_id_181266b1_fk_transport_route_id FOREIGN KEY (route_id)
    REFERENCES public.transport_route (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS transport_ridelog_route_id_181266b1
    ON public.transport_ridelog(route_id);


ALTER TABLE IF EXISTS public.transport_route
    ADD CONSTRAINT transport_route_bus_id_1afbcbd5_fk_transport_bus_id FOREIGN KEY (bus_id)
    REFERENCES public.transport_bus (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS transport_route_bus_id_1afbcbd5
    ON public.transport_route(bus_id);


ALTER TABLE IF EXISTS public.transport_routestop
    ADD CONSTRAINT transport_routestop_route_id_ccb3f331_fk_transport_route_id FOREIGN KEY (route_id)
    REFERENCES public.transport_route (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS transport_routestop_route_id_ccb3f331
    ON public.transport_routestop(route_id);


ALTER TABLE IF EXISTS public.transport_studentrider
    ADD CONSTRAINT transport_studentrid_student_id_c914bca2_fk_students_ FOREIGN KEY (student_id)
    REFERENCES public.students_student (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS transport_studentrider_student_id_c914bca2
    ON public.transport_studentrider(student_id);


ALTER TABLE IF EXISTS public.transport_studentrider
    ADD CONSTRAINT transport_studentrider_route_id_62d017c2_fk_transport_route_id FOREIGN KEY (route_id)
    REFERENCES public.transport_route (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS transport_studentrider_route_id_62d017c2
    ON public.transport_studentrider(route_id);

END;