# Generated by Django 6.0.3 on 2026-03-13 03:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BehaviorIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="معرّف السجل",
                    ),
                ),
                (
                    "school_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="معرّف المدرسة"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="السنة الأكاديمية",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="الفصل الدراسي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("final", "نهائي"),
                            ("archived", "مؤرشف"),
                        ],
                        default="draft",
                        max_length=24,
                        verbose_name="حالة السجل",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الواقعة"
                    ),
                ),
                (
                    "narrative",
                    models.TextField(
                        blank=True, null=True, verbose_name="تفاصيل الواقعة"
                    ),
                ),
                (
                    "evidence_ref",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="مرجع الدليل",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منشئ السجل",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BehaviorCommittee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="معرّف السجل",
                    ),
                ),
                (
                    "school_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="معرّف المدرسة"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="السنة الأكاديمية",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="الفصل الدراسي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("final", "نهائي"),
                            ("archived", "مؤرشف"),
                        ],
                        default="draft",
                        max_length=24,
                        verbose_name="حالة السجل",
                    ),
                ),
                ("meeting_date", models.DateTimeField(verbose_name="تاريخ الاجتماع")),
                ("decision", models.TextField(verbose_name="القرار")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منشئ السجل",
                    ),
                ),
                (
                    "incident",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="behavior.behaviorincident",
                        verbose_name="الواقعة",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BehaviorSanction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="معرّف السجل",
                    ),
                ),
                (
                    "school_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="معرّف المدرسة"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="السنة الأكاديمية",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="الفصل الدراسي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("final", "نهائي"),
                            ("archived", "مؤرشف"),
                        ],
                        default="draft",
                        max_length=24,
                        verbose_name="حالة السجل",
                    ),
                ),
                (
                    "sanction_type",
                    models.CharField(max_length=32, verbose_name="نوع الإجراء"),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="تاريخ البدء"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منشئ السجل",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="behavior.behaviorincident",
                        verbose_name="الواقعة",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OffenseCode",
            fields=[
                (
                    "form_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="معرّف السجل",
                    ),
                ),
                (
                    "school_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="معرّف المدرسة"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="السنة الأكاديمية",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="الفصل الدراسي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("final", "نهائي"),
                            ("archived", "مؤرشف"),
                        ],
                        default="draft",
                        max_length=24,
                        verbose_name="حالة السجل",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        verbose_name="رمز المخالفة",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MINOR", "بسيطة"),
                            ("MOD", "متوسطة"),
                            ("MAJOR", "جسيمة"),
                        ],
                        max_length=6,
                        verbose_name="الخطورة",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منشئ السجل",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="behaviorincident",
            name="offense_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="behavior.offensecode",
                verbose_name="رمز المخالفة",
            ),
        ),
    ]
