# Generated by Django 6.0.3 on 2026-03-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("behavior", "0002_alter_behaviorcommittee_form_uuid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="behaviorcommittee",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="behaviorincident",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="behaviorsanction",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="offensecode",
            name="created_by",
        ),
    ]
