# Generated by Django 6.0.3 on 2026-03-13 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=16, verbose_name="الإجراء")),
                ("entity", models.CharField(max_length=64, verbose_name="الكيان")),
                ("entity_id", models.UUIDField(verbose_name="معرّف الكيان")),
                ("ts", models.DateTimeField(auto_now_add=True, verbose_name="التوقيت")),
                (
                    "meta",
                    models.JSONField(
                        blank=True, null=True, verbose_name="بيانات إضافية"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الفاعل",
                    ),
                ),
            ],
            options={
                "ordering": ["-ts"],
                "indexes": [
                    models.Index(
                        fields=["entity", "entity_id", "ts"],
                        name="audit_audit_entity_56f693_idx",
                    )
                ],
            },
        ),
    ]
