# Generated by Django 5.0.3 on 2026-03-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0002_alter_permission_id_alter_role_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permission",
            options={"verbose_name": "صلاحية", "verbose_name_plural": "صلاحيات"},
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "دور", "verbose_name_plural": "أدوار"},
        ),
        migrations.AlterModelOptions(
            name="rolepermission",
            options={
                "verbose_name": "ربط دور بصلاحية",
                "verbose_name_plural": "ربط الأدوار بالصلاحيات",
            },
        ),
        migrations.AlterModelOptions(
            name="userrole",
            options={
                "verbose_name": "ربط مستخدم بدور",
                "verbose_name_plural": "ربط المستخدمين بالأدوار",
            },
        ),
    ]
