# Generated by Django 6.0.3 on 2026-03-12 22:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicVisit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school_id", models.UUIDField()),
                ("academic_year", models.CharField(max_length=9)),
                ("term", models.CharField(max_length=8)),
                ("form_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_by", models.UUIDField()),
                ("status", models.CharField(default="draft", max_length=24)),
                ("visit_date", models.DateField()),
                ("medical_note", models.BinaryField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school_id", models.UUIDField()),
                ("academic_year", models.CharField(max_length=9)),
                ("term", models.CharField(max_length=8)),
                ("form_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_by", models.UUIDField()),
                ("status", models.CharField(default="draft", max_length=24)),
                ("medication_name", models.CharField(max_length=128)),
                ("dose", models.CharField(max_length=64)),
                ("issued_at", models.DateTimeField()),
                (
                    "clinic_visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="health.clinicvisit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
